### ISSUE TITLE
Remake trunk build page

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/cellprofiler.github.com-backup#1]
There are lots of old links on the forum and elsewhere to www.cellprofiler.org/cgi-bin/trunk_build.cgi. We need to at least make a static page for this, and eventually redirect it to where the automated builds live.

**Comment by dlogan** [comment]
Executables from the last trunk_build page are stored here for easy access: http://www.broadinstitute.org/~dlogan/CP_executables/trunk_builds/

Not sure how to redirect the old link to the address above though.

**Comment by LeeKamentsky** [comment]
We need to rewrite the trunk build page's CGI script and figure out where to store the files so they can be retrieved from a URL. Currently, there are two local Jenkins servers building these and it would be very handy to have the trunk build page be able to find the latest and make that available.

Cost-wise, these are big things, updated frequently and downloaded often so perhaps they should not live on Amazon S3? Or we should be very careful to delete the old ones after a new one is built?

**Comment by dlogan** [comment]
Good point -- I don't know the I/O or storage costs for our bucket.  @0x00B1 ?

**Comment by dlogan** [comment]
This could be closed if we could forward this link www.cellprofiler.org/cgi-bin/trunk_build.cgi to www.cellprofiler.org/releases though I don't know how to do that on cellprofiler.github.io

**Comment by 0x00b1** [comment]
@dlogan:

> This could be closed if we could forward this link www.cellprofiler.org/cgi-bin/trunk_build.cgi to www.cellprofiler.org/releases though I don't know how to do that on cellprofiler.github.io

I don’t think there’s any reasonable way to do this

**Comment by dlogan** [comment]
Understood.  As a workaround, I just went through the CP Forum and replaced all (only 11) references of the trunk build cgi page to http://cellprofiler.org/releases/
