### ISSUE TITLE
Remove ExampleFlyImages folder from s3

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/cellprofiler.github.com-backup#17]
Since these images/files are linked to cellprofiler.github.io and not on AWS s3, can we just delete the s3 folder ExampleFlyImages to keep things tidy?  Afaik, that would be fine.

**Comment by alisonkozol** [comment]
I will do this now, but I'm going to wait to organize and clean up the s3 bucket until the new site is more developed.

**Comment by dlogan** [comment]
Very good!
