### ISSUE TITLE
Consolidate Downloads pages 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/cellprofiler.github.com-backup#19]
It seems to me that we should consolidate the pages http://cellprofiler.org/download.html and http://cellprofiler.org/releases/.

http://cellprofiler.org/releases/ is nice and I like the layout and spare look, but it is lacking (imho):
- [ ] Link to CP manual http://d1zymp9ayga15t.cloudfront.net/CPmanual/index.html
- [x] Prerequisites (requirements e.g. Java? What OS versions supported?)
- [ ] Gray out buttons that are not yet linked, e.g. Linux builds 
- [x] Link to http://cellprofiler.org/previousReleases.html

**Comment by dlogan** [comment]
- [x] Link on index page to http://cellprofiler.org/download.html don't point to cellprofiler.org/releases, unlike the menu links changed today

**Comment by N3llz** [comment]
Solved by [#80](https://github.com/CellProfiler/cellprofiler.github.com/pull/80)
