### ISSUE TITLE
Make redirects for all old .shtml pages to their new .html

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/cellprofiler.github.com-backup#2]
I have found a number of old, dead links that point to .shtml pages.  Search svn for these and ensure that they all have redirects like that in, e.g. published_pipelines.html

**Comment by dlogan** [comment]
Here's a list to check that I got from svn below. Basically, find the associated html page (assuming it still exists) and make sure it has (as an example) "redirect_from: /about.shtml" in the header lines flanked by "---" above and below. 

./about.shtml
./archives.shtml
./citations.shtml
./CP_citers.shtml
./cpa_examples.shtml
./developers.shtml
./developersOLD.shtml
./download.shtml
./downloadCPA.shtml
./downloadOLD.shtml
./examples.shtml
./faq.shtml
./gettingStarted.shtml
./impact.shtml
./index.shtml
./install.shtml
./install_1.0.shtml
./interfaces.shtml
./jobs.shtml
./linux.shtml
./manuals.shtml
./outreach.shtml
./PNAS2009.shtml
./press.shtml
./previousReleases.shtml
./previousReleasesCPA.shtml
./published_pipelines.shtml
./supportplan.shtml
./tutorials.shtml
./wormtoolbox/index.shtml

**Comment by alisonkozol** [comment]
Please note the following deleted pages from your list:
archives
cp_citers
pa_examples
developers
developoersOLD
./downloadOLD.shtml
install
install1.0
jobs

All others have been updated
