### ISSUE TITLE
Add note about Java requirements on releases page 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/cellprofiler.github.com-backup#20]
Users of Beta (2.2.0) and presumably Nightly (2.3) are getting errors on startup that are fixed by installing the Java 64-bit JRE 8.

We should add a note at the bottom of each of the sections (Beta and Nightly) of http://cellprofiler.org/releases/index.html that says something like:

"Requirements: Java SE Runtime Environment 8" linked to   http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
We can update the link if Oracle changes it.

@LeeKamentsky @0x00B1 Any other requirements worth noting? Mac OS 10.6+ (just guessing)? Windows 64-bit?

**Comment by LeeKamentsky** [comment]
Definitely 64-bit Windows. I am hoping that's a given at this point.

**Comment by dlogan** [comment]
Fixed with 23e73cfe182d850e236acbeadde04398d7fbe8c9
