### ISSUE TITLE
CPA version 11710 is missing from the old releases page

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/cellprofiler.github.com-backup#33]
CPA version 11710 which was the latest release for a long time is not available on this page:
http://cellprofiler.org/previousReleasesCPA.html

_But_ it is available still here:
http://cellprofiler.org/downloadCPA.html
IMHO this downloadCPA.html page should be removed (#31) once the 11710 version is linked on the  previousReleasesCPA.html page

**Comment by N3llz** [comment]
Solved by [#80](https://github.com/CellProfiler/cellprofiler.github.com/pull/80)
