### ISSUE TITLE
about page continuously redirecting

### ISSUE THREAD

**Issue by alisonkozol** [CellProfiler/cellprofiler.github.com-backup#37]
I've tried redirecting from:

about.html
about.shtml

but nothing changed. Not sure if that's the issue..

**Comment by mcquin** [comment]
I'm not sure what the issue is. What behavior are you seeing? @alisonkozol

**Comment by N3llz** [comment]
_This is Alison writing from Jeanelle's account_

It weirdly works now. All I had to do was create an issue :-)
