### ISSUE TITLE
Update published_pipelines

### ISSUE THREAD

**Issue by braymp** [CellProfiler/cellprofiler.github.com-backup#38]
Not sure if this is the best place, or whether tagging @N3llz is better.

The Dordea paper has been accepted/published so the mention on http://cellprofiler.org/published_pipelines.html should get promoted to the upper list

**Comment by dlogan** [comment]
And my name should be added too (as it is here https://personal.broadinstitute.org/anne/publications.html)

**Comment by bledford87** [comment]
Complete. @shntnu I'm not a contributor on this repo, so I can't close this issue. Can you help with my permissions?
