### ISSUE TITLE
Tracer page broken: 404

### ISSUE THREAD

**Issue by braymp** [CellProfiler/cellprofiler.github.com-backup#5]
http://cellprofiler.org/tracer

**Comment by alisonkozol** [comment]
Page is up with most links functioning. I am unable to fix header. @0x00B1 can you tell me how to do that?

**Comment by rystell** [comment]
Tracer page is still broken 404

**Comment by dlogan** [comment]
@rystell I posted this on the (apparently) new site here: https://github.com/CellProfiler/cellprofiler.github.com/issues/28  

So I suggest keeping this issue closed here.
