### ISSUE TITLE
cellprofiler.org/linux.shtml needs updating

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/cellprofiler.github.com-backup#6]
[This user on the Forum](http://forum.cellprofiler.org/t/urls-down-for-yum-repo-and-makefile-builds/3036) pointed out that the CentOS linux system here is broken.  I fixed the shtml-> html redirect, but we need to re-link this on cellprofiler.org
`linux@ -> /imaging/web/linux_repositories/htdocs/linux`

**Comment by LeeKamentsky** [comment]
The RPMs were served from the website. My guess is that they are not there.
They are large. I would not put them into the repo - it would increase the
size to multiple gigabytes. That's the sort of thing that GIT is really not
too good at and Github has a strict limitation that you can't have files
that are larger than 100 Mb.

What are the alternatives to the repo?

**Comment by dlogan** [comment]
Right, big files go into our S3 bucket.  I can put the RPMs and the source files there.  Just making sure - will yum work with the static github.io pages?

**Comment by LeeKamentsky** [comment]
If everything has the same URLs as it did previously, all should work. If you put the files there, I can test using my DigitalOcean account and a VM.

**Comment by dlogan** [comment]
OK, all the files in cellprofiler.org/linux have been uploaded to s3.  @LeeKamentsky can you try the yum repo with the instructions at http://cellprofiler.org/linux.html?

**Comment by LeeKamentsky** [comment]
Nope. Can't find the following:
http://cellprofiler.org/linux/centos6/repodata/repomd.xml

**Comment by dlogan** [comment]
Fixed now.  The yum repo config file needed a cloudfront URL rather tan cellprofiler.org domain. Tested on Lee's Digital Ocean machine and it worked
