### ISSUE TITLE
The link to the HTML manual points to PDF

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/cellprofiler.github.com-backup#9]
The bottom of this page (and maybe elsewhere?): http://cellprofiler.org/download.html

**Comment by dlogan** [comment]
The html link is fixed now.  But a couple lingering issues:
- Module help does not show up in Google -- will this fix help that?
- The _trackPageView references "/download/manualHTML" -- I have no idea, but is that correct for tracking clicks?

**Comment by bledford87** [comment]
Obsolete since migrating to OpenScholar.
